### ISSUE TITLE
Error in ParseDataFeedJSON(GA.Data) on Custom Dimension User_ID

### ISSUE THREAD

**Issue by eliasah** [Tatvic/RGoogleAnalytics#30]
Hello, I'm trying to access a custom dimension "ga:dimensionUser_ID" but it's return the following Error : 

```
Error in ParseDataFeedJSON(GA.Data) : 
  code : 400 Reason : Unknown dimension(s): ga:dimensionUser_ID
```

This is a valid dimension according to the combinations from the [Google Analytics API Reference Guide](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=custom_variables_or_columns&jump=ga_dimensionxx). 

Is there a way to deal with that ?

Thanks !

**Comment by MMMdata** [comment]
@eliasah custom dimensions cannot be referenced by name, but rather are referenced by index number. Go into your GA admin panel to find out in which slot you're saving the `User_ID` custom dimension, and replace `User_ID` with that number. For example, if you find that you're saving the `User_ID` in custom dimension slot 3, you would query `ga:dimension3` instead of `ga:dimensionUser_ID`.

**Comment by eliasah** [comment]
That sounds great ! Thank you. :)
