### ISSUE TITLE
Problems whith filters "ga:sourceMedium=~yandexmar.+"

### ISSUE THREAD

**Issue by veseliy** [Tatvic/RGoogleAnalytics#7]

**Comment by jdeboer** [comment]
I wonder if the issue is to do with the need to URL encode each of the query parameters, particularly filters and segments. In the [ganalytics](https://github.com/jdeboer/ganalytics) R package I addressed this using R's built-in `URLencode` function but also by manually encoding '`+`' characters as `%2B`, as seen here in the [`form_url` function](https://github.com/jdeboer/ganalytics/blob/master/R/GaApiRequest.R#L131). I hope that helps.

**Comment by veseliy** [comment]
Yep. Thx. Its working

**Comment by shahkushan1** [comment]
@jdeboer Thanks for the assist. Let me test that out on my system.

**Comment by veseliy** [comment]
@shahkushan1we have already disscused this

**Comment by siemarie** [comment]
So am I understanding correctly that there is no way to bypass this error if you just want it to return zero results? I am looping through a series of URLs much like @slarty667 and sometimes it would naturally happen that, for example, a particular URL did not have any conversions over a given time period. Stopping my loop because no results were found is really an annoying feature.

**Comment by BobbyBarbeau** [comment]
@siemarie see a [workaround](https://github.com/Tatvic/RGoogleAnalytics/issues/8#issuecomment-126561275) I've used that I just posted in issue #8
